### ISSUE TITLE
[Content] Migration checklist

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#24]
List of things to remember or todos for the content migration:

For each locale:

- [x] promotion pages: 
  - [x] before import, generate a promotion list for conversion to banner
  - [x] copy all promotions docx
  - [x] lower case folder names and filenames
- [x] author pages:
  - [x] copy all
  - [x] convert all to docx
- [x] topic pages:
  - [ ] copy all
  - [x] copy taxonomy.xlsx
  - [ ] transform - add "article feed" block tag config
- [x] gnav
  - [x] copy / paste existing HTML gnav into Word gnav
- [x] footer
  - [x] copy / paste existing HTML footer into Word footer
- [x] articles
  - [x] copy (overwrite `.docx` and remove `.md`) imported articles from temp sharepoint to theblog sharepoint
- [x] manually sync index pages with latest content

**Comment by kptdobe** [comment]
Still WIP: topic page. See #54.
